# Generated by Django 3.1.6 on 2021-02-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
